/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_admin (void);
GtkWidget* create_kamel_fardi_etudiant_window (void);
GtkWidget* create_kamel_fardi_ajout_etudiant_window1 (void);
GtkWidget* create_kamel_fardi_modifier_window (void);
GtkWidget* create_kamel_fardi_afficher_window (void);
GtkWidget* create_kamel_fardi_ajout_hint_window (void);
GtkWidget* create_kamel_fardi_rechercher_faild_window (void);
GtkWidget* create_kamel_fardi_dash_board_window (void);
GtkWidget* create_kamel_fardi_bien_ajoutee_window (void);
