/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_admin (void);
GtkWidget* create_kamel_fardi_etudiant_window (void);
GtkWidget* create_kamel_fardi_etudiant_gestion_etudiants (void);
